### ISSUE TITLE
Project Specification Document

### ISSUE THREAD

**Issue by qlanduril** [OvgumSezen/CS491-Project#1]
Project Specification Document Guideline:
The project specifications report should provide a brief description and requirements of the proposed project. This document must also contain a section that discusses the project constraints such as economic, environmental, social, political, ethical, health and safety, manufacturability, and sustainability. In addition, a discussion of the professional and ethical responsibilities relevant to the project must also be included in a separate section. Copies of the Project Specification Report must be returned to the project supervisor and the course instructors.

One example organization of this report is as follows: 

1. Introduction

1.1 Description

1.2 Constraints

1.3 Professional and Ethical Issues

2. Requirements

3. References

[example reports](https://www.google.com/search?q=Bilkent+CS491+Project+Specification+Document+filetype%3Apdf&sourceid=chrome&ie=UTF-8)

**Comment by OvgumSezen** [comment]
Report is done. Thanks everyone. :heart:
