### ISSUE TITLE
Analysis and Requirement Report

### ISSUE THREAD

**Issue by qlanduril** [OvgumSezen/CS491-Project#2]
1. Introduction
2. Current System (if any)
3. Proposed System
 3.1 Overview
 3.2 Functional Requirements
 3.3 Nonfunctional Requirements
 3.4 Pseudo Requirements
 3.5 System Models
  3.5.1 Scenarios
  3.5.2 Use Case Model
  3.5.3 Object and Class Model
  3.5.4 Dynamic Models
  3.5.5 User Interface - Navigational Paths and Screen Mock-ups
4. Other Analysis Elements
 4.1. Consideration of Various Factors in Engineering Design
 4.2. Risks and Alternatives
 4.3. Project Plan
 4.4. Ensuring Proper Teamwork
 4.5. Ethics and Professional Responsibilities
 4.6. Planning for New Knowledge and Learning Strategies
5. Glossary
6. References

**Comment by dorukcaliskan02** [comment]
UML- ARDA OVGUM
UI- GIZEM ONUR
BERKAN JOKER

**Comment by OvgumSezen** [comment]
Link to the current WIP doc: https://docs.google.com/document/d/13Xl9T5bDErRbF2UZbN_vULEvVPgyuW720N-f85Bx4vU/edit#heading=h.28b1i3cmos30

**Comment by OvgumSezen** [comment]
> Link to the current WIP doc: https://docs.google.com/document/d/13Xl9T5bDErRbF2UZbN_vULEvVPgyuW720N-f85Bx4vU/edit#heading=h.28b1i3cmos30

The responsibilities are color coded on the headings. Color codes are as follows:
Red ==> Övgüm
Blue ==> Berkan
Green ==> Arda
Yellow ==> Gizem
Brown ==> Doruk

For parts that require multiple people to work on, the names of the people are noted next to the heading in parenthesis.

This is the initial responsibility distribution, to change them simply use the doc (preferably in accordance with the standards stated above.) and make sure that no part is left without a person assigned to it.

Thanks
